name: ywcaofbombay
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 10.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^1.0.0
  cloud_firestore: ^2.5.3
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  firebase_storage: ^10.0.3
  firestore_search: ^0.1.3
  drawerbehavior: ^2.2.1
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  provider: ^6.0.0
  auto_size_text: ^3.0.0-nullsafety.0

  image_picker: ^0.8.4
  flutter_easyloading: ^3.0.3
  date_time_picker: ^2.1.0
  photo_view: ^0.12.0 # zoom_image.dart
  url_launcher: ^6.0.10
  shared_preferences: ^2.0.7
  after_layout: ^1.1.0
  vibration: ^1.7.4-nullsafety.0
  share: ^2.0.4
  open_mail_app: ^0.3.0
  flutter_phone_direct_caller: ^2.0.0
  intl: ^0.17.0
  get: ^4.3.8
  firebase_messaging: ^10.0.8
  firebase_analytics: ^8.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/circles.svg
    - assets/images/circles-encoded.svg
    - assets/images/circle-design.png
    - assets/images/logo.png
    - assets/images/logo-with-text.png
    - assets/images/logo-with-text-border.png
    - assets/images/logo-with-text-border-round.png
    - assets/images/logo-with-text.png
    - assets/images/logo-with-text-round.png
    - assets/images/contact_us/hostel.png
    - assets/images/contact_us/office.png
    - assets/images/about_us/membership.png
    - assets/images/about_us/Ywca_spotlight_1.jpg
    - assets/images/about_us/Ywca_spotlight_2.jpg
    - assets/images/about_us/Ywca_spotlight_3.jpg
    - assets/images/about_us/Ywca_spotlight_4.jpg
    - assets/images/about_us/Ywca_spotlight_5.jpg
    - assets/images/initiatives/piya/1-walk-for-freedom.jpeg
    - assets/images/initiatives/piya/2-walkathon.jpg
    - assets/images/initiatives/piya/3-a-trek-to-kaldurg-fort.jpg
    - assets/images/initiatives/piya/4-interschool-competition.jpeg
    - assets/images/initiatives/piya/5-dance-therapy-by-piya.jpeg
    - assets/images/initiatives/piya/6-piya.jpeg
    - assets/images/initiatives/asha_kiran/1-annual-day.jpg
    - assets/images/initiatives/asha_kiran/2-sports-day.jpg
    - assets/images/initiatives/asha_kiran/3-training-of-puppeteers.png
    - assets/images/initiatives/asha_kiran/4-workshop-on-muslim-legal-rights.png
    - assets/images/initiatives/asha_kiran/5-cartoon-making-workshop.png
    - assets/images/initiatives/asha_kiran/6-self-defence-training.jpg
    - assets/images/initiatives/asha_kiran/7-annual-day-celebration.jpeg
    - assets/images/initiatives/pasi/1-panel-discussion-on-women-and-social-media.jpg
    - assets/images/initiatives/pasi/2-paralegal-training.png
    - assets/images/initiatives/pasi/3-session-on-rti.jpg
    - assets/images/initiatives/pasi/4-life-and-struggle-of-transgender.png
    - assets/images/initiatives/pasi/5-childrens-day-celebration.jpg
    - assets/images/initiatives/wdu/1-nutritious-food-competition.jpeg
    - assets/images/initiatives/wdu/2-childrens-programme.jpeg
    - assets/images/initiatives/wdu/3-bakery-certificate-competition.jpeg
    - assets/images/initiatives/wdu/4-debate-competition.png
    - assets/images/initiatives/wdu/5-bakery-practical.jpg
    - assets/images/initiatives/wdu/6-rally-on-human-rights-awareness.jpg
    - assets/images/initiatives/wdu/7-annual-sports-day.jpg
    - assets/images/initiatives/wdu/8-bunny-tamtola.jpg
    - assets/images/initiatives/wdu/9-peace-march.jpg
    - assets/images/initiatives/wdu/10-childrens-camp.jpeg
    - assets/images/initiatives/wdu/11-disaster-management-training.jpeg
    - assets/images/initiatives/wdu/12-anand-mela.jpeg
    - assets/images/initiatives/ywca_hostels/1-abh-in-night.jpg
    - assets/images/initiatives/ywca_hostels/2-ddh.jpg
    - assets/images/initiatives/ywca_hostels/3-national-festival-celebration.jpg
    - assets/images/initiatives/ywca_hostels/4-dining-room-lwh.png
    - assets/images/initiatives/ywca_hostels/5-ddh-lounge.jpg
    - assets/images/initiatives/ywca_hostels/6-lwh-building.jpeg
    - assets/images/initiatives/public_relations/1-staff-training.jpeg
    - assets/images/initiatives/public_relations/2-music-around-the-world.jpg
    - assets/images/initiatives/public_relations/3-training-on-gst.jpg
    - assets/images/initiatives/shelter_homes/1-inauguration-of-ummeed-shelter-home.jpeg
    - assets/images/initiatives/shelter_homes/2-inauguration-of-ummeed-shelter-home.jpg
    - assets/images/initiatives/shelter_homes/3-ashraya.jpeg
    - assets/images/initiatives/memberships/1-ekta.jpeg
    - assets/images/initiatives/memberships/2-evening-of-carols.jpg
    - assets/images/initiatives/memberships/3-sacred-music.jpg
    - assets/images/initiatives/memberships/4-world-membership-day.jpg
    - assets/images/initiatives/memberships/5-christmas-programme.jpeg
    - assets/images/initiatives/international_centre/1-ic-review.jpg
    - assets/images/initiatives/international_centre/2-family-room.png
    - assets/images/initiatives/international_centre/3-waiting-room.png
    - assets/images/initiatives/international_centre/4-reception.png
    - assets/images/initiatives/spiritual_emphasis/1-world-day-of-prayer.jpg
    - assets/images/initiatives/spiritual_emphasis/2-ywca-n-ymca-week-of-prayer.jpg
    - assets/images/initiatives/spiritual_emphasis/3-week-of-prayer.jpeg
    - assets/images/initiatives/general/1-paralegal-training.jpg
    - assets/images/initiatives/general/2-agm.jpg
    - assets/images/initiatives/general/3-best-ngo-award.jpg
    - assets/images/initiatives/general/4-best-ngo-award.jpg
    - assets/images/extras/image20.jpeg
    - assets/images/success_stories/1-success-stories.png
    - assets/images/success_stories/2-a-slice-of-support.png
    - assets/images/success_stories/3-a-stitch-in-time.png
    - assets/images/success_stories/4-beauty-with-brains.png
    - assets/images/success_stories/5-food-for-thought.png
    - assets/images/success_stories/6-hair-tales.png
    - assets/images/success_stories/7-nursing-aid.png
    - assets/images/success_stories/8-promoting-education.png
    - assets/images/success_stories/9-aasra.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: RacingSansOne
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
    - family: LobsterTwo
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
