const DATA = [
  {
    "firstName": "Priyal",
    "lastName": "Vaz",
    "phoneNumber": "7977002243",
    "emailId": "pvaz@gmail.com",
    "nearestCenter": "Chembur",
    "placeOfWork": "DBIT",
    "profession": "Student",
  },
  {
    "firstName": "Anish",
    "lastName": "Nair",
    "phoneNumber": "7977002243",
    "emailId": "pvaz@gmail.com",
    "nearestCenter": "Chembur",
    "placeOfWork": "DBIT",
    "profession": "Student",
  },
  {
    "firstName": "Ruvin",
    "lastName": "Rodridues",
    "phoneNumber": "7977002243",
    "emailId": "pvaz@gmail.com",
    "nearestCenter": "Chembur",
    "placeOfWork": "DBIT",
    "profession": "Student",
  },
  {
    "firstName": "Karan",
    "lastName": "Doshi",
    "phoneNumber": "7977002243",
    "emailId": "pvaz@gmail.com",
    "nearestCenter": "Chembur",
    "placeOfWork": "DBIT",
    "profession": "Student",
  },
  {
    "firstName": "Priyal Vaz",
    "lastName": "Priyal Vaz",
    "phoneNumber": "7977002243",
    "emailId": "pvaz@gmail.com",
    "nearestCenter": "Chembur",
    "placeOfWork": "DBIT",
    "profession": "Student",
  },
];
